/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moch Alvy Nur Ramadh
 */
public class Latihan_4_2 extends javax.swing.JFrame {
    
    int nilai_a,nilai_b;
    boolean hasil;
    
    /**
     * Creates new form Latihan_4_2
     */
    public Latihan_4_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpertama = new javax.swing.JTextField();
        txtkedua = new javax.swing.JTextField();
        btnsama = new javax.swing.JButton();
        btntidaksama = new javax.swing.JButton();
        btnlebih = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnlebihsama = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txthasil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnkurangsama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("PROGRAM OPERATOR PEMBANDING");

        jLabel2.setText("NILAI A");

        jLabel3.setText("NILAI B");

        txtpertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpertamaActionPerformed(evt);
            }
        });

        btnsama.setText("==");
        btnsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsamaActionPerformed(evt);
            }
        });

        btntidaksama.setText("!=");
        btntidaksama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntidaksamaActionPerformed(evt);
            }
        });

        btnlebih.setText(">");
        btnlebih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlebihActionPerformed(evt);
            }
        });

        btnkurang.setText("<");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        btnlebihsama.setText(">=");
        btnlebihsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlebihsamaActionPerformed(evt);
            }
        });

        jLabel4.setText("HASIL");

        jLabel5.setText("DIBUAT OLEH : RICHI DWI A");

        btnkurangsama.setText("<=");
        btnkurangsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangsamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtpertama, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkedua, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnsama)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btntidaksama)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnlebih)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnkurang)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnlebihsama)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnkurangsama)))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkurang)
                    .addComponent(btnlebihsama)
                    .addComponent(btnsama)
                    .addComponent(btnkurangsama)
                    .addComponent(btnlebih)
                    .addComponent(btntidaksama))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpertamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpertamaActionPerformed

    private void btnsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_a = Integer.valueOf(txtpertama.getText());
        
        hasil = (nilai_a == nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnsamaActionPerformed

    private void btntidaksamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntidaksamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_a = Integer.valueOf(txtpertama.getText());
        
        hasil = (nilai_a != nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btntidaksamaActionPerformed

    private void btnlebihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlebihActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_a = Integer.valueOf(txtpertama.getText());
        
        hasil = (nilai_a > nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnlebihActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_a = Integer.valueOf(txtpertama.getText());
        
        hasil = (nilai_a < nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnlebihsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlebihsamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_a = Integer.valueOf(txtpertama.getText());
        
        hasil = (nilai_a >= nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnlebihsamaActionPerformed

    private void btnkurangsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangsamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_a = Integer.valueOf(txtpertama.getText());
        
        hasil = (nilai_a <= nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnkurangsamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan_4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan_4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan_4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan_4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan_4_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnkurangsama;
    private javax.swing.JButton btnlebih;
    private javax.swing.JButton btnlebihsama;
    private javax.swing.JButton btnsama;
    private javax.swing.JButton btntidaksama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtkedua;
    private javax.swing.JTextField txtpertama;
    // End of variables declaration//GEN-END:variables
}
